//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int Id { get; set; }
        public int OrdenId { get; set; }
        public int TableId { get; set; }
        public bool Status { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Tables Tables { get; set; }
    }
}
