//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public decimal Total { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
